project:
  type: website
  resources:
    - files/AkshayShankarCV.pdf

website:
  title: "Akshay Shankar"
  site-url: "https://20akshay00.github.io/"
  description: "A personal website with the latest updates on my research, projects, and thoughts."
  navbar:
    search: true
    collapse-below: lg
    right:
      - href: research.qmd
        text: Research
      - href: tidbits.qmd
        text: Tidbits
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: gallery.qmd
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=8XmbbYgAAAAJ
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0009-0009-9521-1188
      - icon: github
        href: https://github.com/20akshay00
      - icon: linkedin
        href: https://linkedin.com/in/20akshay00
      - text: "{{< fa brands itch-io >}}"
        href: https://20akshay00.itch.io/
format:
  html:
    theme: 
      - journal
      - custom.scss
    css: styles.css

execute:
  freeze: false
  cache: true
  