---
title: "Resources"
subtitle: "A collection of works to learn new things."
permalink: /resources/
toc: false
title-block-banner: true
format:
  html:
    page-layout: full
---

In today's world, there is no limit to the content that we can access for learning new things. I have often burnt many days simply collecting and vetting these resources, making it quite hard to make tangible progress in actually learning the content. This page is dedicated to compiling any useful resources that I have found, in the hopes that someone else may find it helpful.

::: {.callout-note appearance="simple"}
**Note:** This list was curated before the ubiquity of generative AI. While the landscape of learning has since changed, I still maintain this collection for my own reference.
:::

::: {.panel-tabset}

## Julia

### Intro to language features
- [**Official docs**](https://docs.julialang.org/en/v1/): Pretty good documentation for an overview of what the language offers.
- [**MIT Computational Thinking**](https://computationalthinking.mit.edu): Great gateway into Julia for those already familiar with programming and/or numerical computation. 
- **Misc. introductory courses:** [Scientific programming in Julia](https://juliateachingctu.github.io/Scientific-Programming-in-Julia/dev/), [Julia for economists](https://youtube.com/playlist?list=PLbuwVVKCI3sRW0Y5ehBFwdFVuyuy87ram&si=kCy1lmn-C20OcKWg)
- [**Modern workflows**](https://modernjuliaworkflows.github.io/)

### Numerical techniques
- **Some comprehensive and broad books:** [Numerical methods in scientific computing](https://www.equalsharepress.com/media/NMFSC.pdf), [Fundamentals of Numerical Computation](http://tobydriscoll.net/fnc-julia/frontmatter.html)
- [**Parallel Computing and Scientific Machine Learning**](https://book.sciml.ai/): An excellent course taught by [Chris Rackauckas](https://www.chrisrackauckas.com/), a very knowledgeable and prolific contributor to the DifferentialEquations.jl ecosystem.

### Video and Community
- [**Official Julia Language**](https://www.youtube.com/@TheJuliaLanguage): A literal treasure trove of information containing lectures from most Julia related events (most notably, the annual JuliaCon). It is certainly worth going through the ~4 hour workshops from previous JuliaCons. These cover a large variety of topics spanning from basic language features, metaprogramming and interactive plotting to developing and publishing your own packages.
- [**Doggo.jl**](https://youtube.com): Regular exploration into various random Julia concepts and packages.
- [**Discourse**](https://discourse.julialang.org/): The primary forum for discussion
- [**Zulip**](https://julialang.zulipchat.com/): A more texting oriented platform
- [**Discord**](https://discord.gg/C5h9D4j): Unofficial server for discussion

### Package ecosystem
- **List of all packages:** [JuliaHub](https://juliahub.com/ui/Packages), [JuliaPackages](https://juliapackages.com/), [Julia.jl](https://github.com/svaksha/Julia.jl)
- [**Assorted list of domain-specific packages**](https://github.com/frankwswang?tab=stars): Maintained by [Weishi Wang](https://github.com/frankwswang)

## Game Development

### Engine and Logic
- [**Official documentation**](https://docs.godotengine.org/en/stable/index.html): Fairly good as far as documentation goes. There are also few text tutorials for beginner projects.
- [**The ultimate introduction to Godot 4**](https://youtube.com): An excellent introduction to what Godot offers if already familiar with programming.
- [**Godot 4 - Code Architecture**](https://youtube.com): An intermediate course on how to make good design choices to write a scalable and maintainable codebase for your Godot game.
- [**Godotneers**](https://youtube.com): Assortment of tutorials on general concepts and systems in games.
- [**KidsCanCode:**](http://kidscancode.org): A really useful resource for implementation of specific mechanics/systems in games (despite the rather goofy name!).
- [**GDQuest**](https://www.gdquest.com/): Similar to KidsCanCode.
- [**Game Programming Patterns**](https://gameprogrammingpatterns.com/): Design patterns to make code cleaner, easier to understand, and faster.

### Assets
- [**Lospec**](https://lospec.com/): Color palettes for pixel art.
- [**Kenney's asset packs**](https://kenney.nl/): A vaaaast collection of art that is free to use. 
- [**Aseprite:**](https://www.aseprite.org/): A paid (but source available) software to make pixel art. 
- [**Pixelorama:**](https://orama-interactive.itch.io/pixelorama): An open source pixel art software made with Godot.
- [**jsfxr**](https://sfxr.me/): 8-bit retro sfx generator.

### Procedural Animation
- [**Physics-based Animation**](https://iphys.wordpress.com/wp-content/uploads/2020/01/erleben.ea05.pdf): A book on using physics to generate realistic animations in video games.
- [**Advanced Character Physics**](https://www.cs.cmu.edu/afs/cs/academic/class/15462-s13/www/lec_slides/Jakobsen.pdf): A paper on the basic elements of physically-based modelling as implemented in [Hitman: Codename 47](https://store.steampowered.com/app/6900/Hitman_Codename_47/).
- [**Limbo-style spider**](https://youtube.com)
- [**Worms, snakes and lizards**](https://youtube.com)
- [**Swinging Gibbon**](https://youtube.com)

## Visualization

### General Tools
- [**Excalidraw**](https://excalidraw.com/): An online whiteboard application w/ live collaboration features.
- [**REXpaint**](https://kyzrati.itch.io/rexpaint): A user-friendly ASCII art editor.
- [**Mermaid**](https://mermaid-js.github.io/mermaid/#/): A JavaScript based diagramming and charting tool using markdown-like inputs.   
- [**p5.js**](https://p5js.org/): A javascript library for creative coding.
- [**Explorables**](https://explorabl.es/tools/): A collection of various tools for creating explorable/interactive explanations.
- [**Friends don't let Friends**](https://github.com/cxli233/FriendsDontLetFriends): A guide on designing good visualizations of data.
- [**From Python to Numpy**](https://www.labri.fr/perso/nrougier/from-python-to-numpy): A short book covering advanced usage of numpy.

### Scientific Visualization
- [**Python + Matplotlib**](https://www.labri.fr/perso/nrougier/scientific-visualization.html): Book covering fundamental principles of [matplotlib](https://matplotlib.org/) and good practices to design plots.
- [**Blender for Scientists**](https://youtube.com): YouTube channel introducing 3D Modelling for scientists.
- [**Penrose**](https://penrose.cs.cmu.edu/): Create diagrams by typing notation in plain text, separating logic from visuals.
- [**Creating publication-quality plots in Julia**](https://nextjournal.com/leandromartinez98/tips-to-create-beautiful-publication-quality-plots-in-julia)
- [**VisualPDE**](https://visualpde.com/): Rapid Interactive Simulations of Partial Differential Equation on the web.

### Shaders and Graphics
- [**An introduction to shader art coding**](https://youtube.com): An introductory video tutorial for creative coding with fragment shaders. 
- [**Fragment foundry**](https://hughsk.io/fragment-foundry/chapters/01-hello-world.html): A collection of text-based tutorials for writing fragment shaders on the browser.
- [**Shader school**](https://github.com/stackgl/shader-school): A collection of browser-based tutorials to write fragment and vertex shaders in [GLSL](https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_on_the_web/GLSL_Shaders).
- [**The Art of Code**](https://www.youtube.com/@TheArtofCodeIsCool): An excellent YouTube channel covering a plethora of things that can be made with shaders.
- [**Painting with Math**](https://youtube.com): [Inigo Quilez](https://iquilezles.org/)' YouTube channel on making shader art.
- [**3D Computer Graphics Programming for Beginners**](https://docs.google.com/document/u/0/d/1JwwLYxFMDwuxX4Sc3znE-8jVIQMW1LWjuvYeLpiVf_8/mobilebasic): A selection of resources to learn and tinker with.
- [**ScratchAPixel**](https://www.scratchapixel.com/): Computer graphics programming for regular folks.
- [**Tiny Renderer**](https://github.com/ssloy/tinyrenderer/wiki/Lesson-1:-Bresenham%E2%80%99s-Line-Drawing-Algorithm): Lessons on how [OpenGL](https://learnopengl.com/) works.
- [**LearnWebGPU**](https://eliemichel.github.io/LearnWebGPU/introduction.html) | [**LearnWebGL**](http://learnwebgl.brown37.net/)
- [**Learning Modern 3D Graphics Programming**](https://paroj.github.io/gltut/): A tutorial for learning graphics programming concepts using OpenGL. 
- [**Real Time Rendering**](https://www.amazon.com/Real-Time-Rendering-Fourth-Tomas-Akenine-M%C3%B6ller/dp/1138627003?tag=realtimerenderin): A book on techniques to render geometry in real time. 
- [**GPU Puzzles**](https://gpupuzzles.answer.ai): A series of small, fun, self-contained coding challenges for learning GPU programming.

## Physics

### Blogs and Notes
- [**A Bit Correlated**](https://tpolakovic.github.io/): A short series of posts on quantum mechanics and solid state physics.
- [**This Condensed Life**](https://thiscondensedlife.wordpress.com/): Regular tid-bits on various topics of condensed matter physics.
- [**An introduction to spontaneous symmetry breaking**](https://scipost.org/10.21468/SciPostPhysLectNotes.11)
- [**The Kosterlitz-Thouless phase transition**](https://arxiv.org/abs/2207.13748)
- [**Geometry of variational methods: dynamics of closed quantum systems**](https://arxiv.org/abs/2004.01015)
- [**Quantum Gases**](https://pro.college-de-france.fr/jean.dalibard/index_en.html)

### Lectures
- [**Symmetries and Quantum Mechanics**](https://www.youtube.com/playlist?list=PLDfPUNusx1ErdQhrdAzincNJKgTQahsX_): A short course by [Tobias Osborne](https://www.itp.uni-hannover.de/en/groups/osborne).
- [**Computational Many-Body Physics**](http://www.thp.uni-koeln.de/trebst/Lectures/2021-CompManyBody.shtml), by [Simon Trebst](http://www.thp.uni-koeln.de/trebst/members.shtml).
- [**Topology in condensed matter: Tying quantum knots**](https://topocondmat.org/).
- [**Speaker's corner**](https://virtualscienceforum.org/speakers-corner/): A platform for scientific conferences going fully digital.

## CS and Mathematics

### Formal verification
- [**Xena Project**](https://xenaproject.wordpress.com/): An excellent blog with various articles on dependant type theory and automated theorem proving with Lean 4.
- [**Automated reasoning:**](https://www.amazon.science/blog/a-gentle-introduction-to-automated-reasoning): An introduction to how [Amazon](https://en.wikipedia.org/wiki/Amazon_(company)) utilizes formal verification with Lean 4 in their test suite for various software products.
- [**Busy Beavers**](https://busy-beavers.tigyog.app/): An interactive (paid) course introducing computability theory incuding practical demonstrations using Lean 4 and SAT solvers.

### Software development
- [**Learn C++**](https://www.learncpp.com/): A series of text based tutorials to learn C++ from scratch.
- [**Third bit**](https://third-bit.com): A couple of excellent books covering things from writing good python code for scientific research to how open source projects design their architecture.

## Random tools

### Type-setting
- [**Typst**](https://typst.app/): A very promising LaTeX alternative in early development.
- [**Tex2Typst**](https://qwinsi.github.io/tex2typst-webapp/): A web-app to quickly convert math syntax from TeX to Typst.
- [**Approach Zero**](https://approach0.xyz/search/): A website that lets you search all the Stack Exchange forums by LaTeX equations.
- [**Tables Generator**](https://www.tablesgenerator.com/): A website to generate LaTeX tables with ease.
- [**Mathcha**](https://www.mathcha.io/): A WYSIWYG editor to create math diagrams for use in LaTeX documents.

### General programming stuff
- [**Git Fix Um**](http://sukima.github.io/GitFixUm/): A [TiddlyWiki](https://tiddlywiki.com/) website in a choose-your-own-adventure format to fix all your git troubles.
- [**Ryan's tutorials**](https://ryanstutorials.net/regular-expressions-tutorial/): A series of text tutorials to learn [RegEx](https://en.wikipedia.org/wiki/Regular_expression).

:::x